# Define os serviços (contêineres) que compõem a aplicação.
services:
  # Define o serviço da nossa API.
  api:
    # Constrói a imagem Docker a partir do Dockerfile localizado no diretório atual ('.').
    build: .
    # Define um nome personalizado para o contêiner para fácil identificação.
    container_name: api_escola
    # Mapeia a porta 8000 da máquina host para a porta 8000 do contêiner.
    # Isso permite que você acesse a API em http://localhost:8000.
    ports:
      - "8000:8000"
    # Monta o diretório atual ('.') no diretório '/app' dentro do contêiner.
    # Isso permite o hot-reloading: alterações no código local são refletidas instantaneamente no contêiner.
    volumes:
      - .:/app
    # Comando que será executado quando o contêiner iniciar.
    # Inicia o servidor Uvicorn, tornando a API acessível de fora do contêiner ('0.0.0.0'),
    # e ativa o --reload para reiniciar o servidor automaticamente após mudanças no código.
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload